name=PTSolns_I2Connect_OLED
version=1.0.0
author=PTSolns
maintainer=PTSolns <support@ptsolns.com>
sentence=Library for the PTSolns I2Connect OLED module.
paragraph=Provides a lightweight, independent graphics engine to draw text, shapes, and bitmaps for the 0.96-inch OLED I2Connect module using I2C.
category=Display
url=https://github.com/PTSolns/I2Connect_OLED
architectures=*
includes=PTSolns_I2Connect_OLED.h
